import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import {HeroProviders} from "@/components/HeroProvider"
import { Toaster } from "sonner";
import { BottomBar } from "@/components/BottomBar/BottomBar";

const kanit = Kanit({
  variable: "--font-kanit",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={`${kanit.className} ${kanit.variable} antialiased min-h-screen w-screen`}
      >
        <HeroProviders>
          <div className="flex flex-col h-screen w-full overflow-hidden">
            <div className=" h-full">
              {children}
            </div>
            <div className=" h-[10%] w-full">
              <BottomBar />
            </div>
          </div>
          <Toaster richColors 
          closeButton={true}
          toastOptions={{
            style: {
              fontFamily: 'Kanit, sans-serif',
            },
            className: "KanitFont",
          }} />
        </HeroProviders>
      </body>
    </html>
  );
}
